export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SELECTED_CHAT = 'SELECTED_CHAT';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
